version: "2"

services:

  apexbeat:
    image: verticleio/apexbeat
    ports:
      - 8089:8089

  petclinic:
    image: verticleio/apex-petclinic
    ports:
      - 8080:8080
    volumes:
      - ./apexconfig:/apexconfig

  elasticsearch:
    image: elasticsearch:5
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: kibana:5
    ports:
      - 5601:5601
    links:
      - elasticsearch
